# glowstone.yml is the main configuration file for a Glowstone server
# It contains everything from server.properties and bukkit.yml in a
# normal CraftBukkit installation.
# 
# Configuration entries are documented on the wiki: https://github.com/GlowstoneMC/Glowstone/wiki/Configuration-Guide
# For help, join us on Discord: https://discord.gg/TFJqhsC
server:
    ip: ''
    port: 25565
    name: Glowstone Server
    log-file: logs/log-%D.txt
    online-mode: false
    max-players: 9999
    whitelisted: false
    motd: A Glowstone server
    shutdown-message: Server shutting down.
    allow-client-mods: true
    snooper-enabled: false
    prevent-proxy-connections: true
console:
    use-jline: true
    prompt: '> '
    date-format: HH:mm:ss
    log-date-format: yyyy/MM/dd HH:mm:ss
game:
    gamemode: SURVIVAL
    gamemode-force: false
    difficulty: PEACEFUL
    hardcore: false
    pvp: false
    max-build-height: 256
    announce-achievements: true
    allow-flight: false
    command-blocks: false
    resource-pack: ''
    resource-pack-hash: ''
creatures:
    enable:
        monsters: false
        animals: false
        npcs: false
    limit:
        monsters: 70
        animals: 15
        water: 5
        ambient: 15
    ticks:
        monsters: 1
        animal: 400
folders:
    plugins: plugins
    update: update
    worlds: worlds
    libraries: lib
files:
    permissions: permissions.yml
    commands: commands.yml
    help: help.yml
advanced:
    connection-throttle: 4000
    idle-timeout: 0
    warn-on-overload: true
    exact-login-location: false
    plugin-profiling: false
    deprecated-verbose: 'false'
    compression-threshold: 256
    proxy-support: false
    player-sample-count: 12
    graphics-compute:
        enable: false
        use-any-device: false
    region-file:
        cache-size: 256
        compression: true
    profile-lookup-timeout: 5
    suggest-player-name-when-null-tab-completions: true
extras:
    query-enabled: false
    query-port: 25614
    query-plugins: true
    rcon-enabled: false
    rcon-password: glowstone
    rcon-port: 25575
    rcon-colors: true
world:
    name: world
    seed: ''
    level-type: FLAT
    spawn-radius: 10
    view-distance: 10
    gen-structures: false
    allow-nether: true
    allow-end: true
    keep-spawn-loaded: true
    populate-anchored-chunks: true
    classic-style-water: false
    disable-generation: false
libraries:
    checksum-validation: true
    repository-url: https://repo.glowstone.net/service/local/repositories/central/content/
    download-attempts: 2
    compatibility-bundle: CRAFTBUKKIT
    list: []
